server:
  port: 8089  # Ou outra porta que você quiser

spring:
  datasource:
    url: jdbc:h2:mem:financeapp
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true  # Para acessar o console H2 em http://localhost:8089/h2-console