server:
  port: 8081  # Porta padrão 8089 para dev

spring:
  datasource:
      url: jdbc:postgresql://postgres:5432/finances
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
        show-sql: true
      flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration
        enabled: true
      hikari:
        initialization-fail-timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: evandre297@gmail.com
    password: e i o r a w c w k d c x v v d k  # Use senha de app do Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: rabbitmqbanking
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
  expiration: ${JWT_EXPIRATION:86400000}

encryption:
  key: ${ENCRYPTION_KEY:chave16bytes1234}

credit:
  card:
    limit:
      free: 1
      premium: 3
sms:
  mock:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: ao.com.wundu
  paths-to-match: /api/**

wundu:
  banking:
    api:
      url: http://wundu-banking:8081/api
      key: 123456789SECRETKEY

logging:
  level:
    org:
      springframework:
        security: DEBUG