spring:
  datasource:
     url: jdbc:postgresql://metro.proxy.rlwy.net:45137/railway
     username: postgres
     password: smPvHrbjnPGKBMiBttXIlfdGaVldkmVx
     driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Em prod, usaremos migrações
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: evandre297@gmail.com
    password: e i o r a w c w k d c x v v d k # Use senha de app do Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: wundu-rabbitmq.railway.internal  # Domínio interno do RabbitMQ
    port: 5672
    username: wunduuser
    password: wundupass123
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 5000
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 5000

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
  expiration: 86400000  # 24 horas

encryption:
  key: ${ENCRYPTION_KEY:chave16bytes1234}

credit:
  card:
    limit:
      free: 1
      premium: 3

sms:
  mock:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: ao.com.wundu
  paths-to-match: /api/**

wundu:
  banking:
    api:
      url: https://wundu-banking-production.up.railway.app/api
      key: 123456789SECRETKEY

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081  # Ou outra porta que você quiser

sentry:
  dsn: https://73b8613be02c0114f9038c597c28c575@o4509474527838208.ingest.de.sentry.io/4509474651111504
  in-app-incluse: ao.com.wundu
  send-default-pii: true
  traces-sample-rate: 1.0
  logging:
    enabled: true
    minimum-breadcrumb-level: INFO
    minimum-event-level: ERROR