server:
  port: ${SERVER_PORT:8089}  # Porta padrão 8089 para dev

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:financeapp}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:teste}
    password: ${DB_PASSWORD:teste}
  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}  # Console H2 em /h2-console
      path: /h2-console

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:evandre297@gmail.com}
    password: ${MAIL_PASSWORD:eiorawckdcxvvdvk}  # Use senha de app do Gmail
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
  expiration: ${JWT_EXPIRATION:86400000}

encryption:
  key: ${ENCRYPTION_KEY:chave16bytes1234}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

#server:
#  port: ${SERVER_PORT:8089}
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://kelvinfabio2:lPq9vxc6BvOXwdEE@cluster0.btttn.mongodb.net/financialdb?retryWrites=true&w=majority
#      database: financialdb
#  mail:
#    host: ${MAIL_HOST:smtp.gmail.com}
#    port: ${MAIL_PORT:587}
#    username: ${MAIL_USERNAME:evandre297@gmail.com}
#    password: ${MAIL_PASSWORD:eiorawckdcxvvdvk}
#    properties:
#      mail:
#        smtp:
#          auth: ${MAIL_SMTP_AUTH:true}
#          starttls:
#            enable: ${MAIL_STARTTLS_ENABLE:true}
#
#jwt:
#  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
#  expiration: ${JWT_EXPIRATION:86400000}
#
#encryption:
#  key: ${ENCRYPTION_KEY:chave16bytes1234}