spring:
  datasource:
     url: jdbc:postgresql://metro.proxy.rlwy.net:45137/railway
     username: postgres
     password: smPvHrbjnPGKBMiBttXIlfdGaVldkmVx
     driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Em prod, usaremos migrações
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: evandre297@gmail.com
    password: e i o r a w c w k d c x v v d k # Use senha de app do Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: wundu-rabbitmq.railway.internal
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
  expiration: 86400000  # 24 horas

encryption:
  key: ${ENCRYPTION_KEY:chave16bytes1234}

credit:
  card:
    limit:
      free: 1
      premium: 3

sms:
  mock:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: ao.com.wundu
  paths-to-match: /api/**

wundu:
  banking:
    api:
      url: https://wundu-banking-production.up.railway.app/api
      key: 123456789SECRETKEY

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081  # Ou outra porta que você quiser