spring:
  datasource:
     url: jdbc:postgresql://caboose.proxy.rlwy.net:34168/railway
     username: postgres
     password: ExXojZoKGuCcxIHbNJcEupWhMsdbgoKK
     driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Em prod, usaremos migrações
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: evandre297@gmail.com
    password: e i o r a w c w k d c x v v d k # Use senha de app do Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
  expiration: 86400000  # 24 horas

encryption:
  key: ${ENCRYPTION_KEY:chave16bytes1234}

server:
  port: 8081  # Ou outra porta que você quiser