server:
  port: 8081  # Porta padrão 8089 para dev

spring:
  datasource:
      url: jdbc:postgresql://postgres:5432/finances
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
        show-sql: true
      flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration
        enabled: true
      hikari:
        initialization-fail-timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: evandre297@gmail.com
    password: e i o r a w c w k d c x v v d k  # Use senha de app do Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
  expiration: ${JWT_EXPIRATION:86400000}

encryption:
  key: ${ENCRYPTION_KEY:chave16bytes1234}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

#server:
#  port: ${SERVER_PORT:8089}
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://kelvinfabio2:lPq9vxc6BvOXwdEE@cluster0.btttn.mongodb.net/financialdb?retryWrites=true&w=majority
#      database: financialdb
#  mail:
#    host: ${MAIL_HOST:smtp.gmail.com}
#    port: ${MAIL_PORT:587}
#    username: ${MAIL_USERNAME:evandre297@gmail.com}
#    password: ${MAIL_PASSWORD:eiorawckdcxvvdvk}
#    properties:
#      mail:
#        smtp:
#          auth: ${MAIL_SMTP_AUTH:true}
#          starttls:
#            enable: ${MAIL_STARTTLS_ENABLE:true}
#
#jwt:
#  secret: ${JWT_SECRET:ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890}
#  expiration: ${JWT_EXPIRATION:86400000}
#
#encryption:
#  key: ${ENCRYPTION_KEY:chave16bytes1234}