server:
  port: 8089  # Ou outra porta que você quiser

spring:
  datasource:
    url: jdbc:h2:mem:financeapp
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true  # Para acessar o console H2 em http://localhost:8089/h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: evandre297@gmail.com
    password: e i o r a w c w k d c x v v d k
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ThisIsAVeryLongAndSecureSecretKeyForJWTThatIsAtLeast64CharactersLong1234567890
  expiration: 86400000  # 24 horas em milissegundos

encryption:
  key: chave16bytes1234  # Chave de 16 bytes para AES

# Twilio (SMS) - Simulado por enquanto
#twilio:
#  account:
#    sid: "your-twilio-account-sid"
#  auth:
#    token: "your-twilio-auth-token"
#  phone:
#    number: "+224928878381"